# Generated by Django 5.1.3 on 2024-11-17 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('founding_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(max_length=50)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investor', models.JSONField(default=list)),
                ('founders', models.ManyToManyField(related_name='startups', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Startups',
            },
        ),
    ]
