# Generated by Django 5.1.3 on 2024-11-17 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='startups.startup')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
