# Generated by Django 5.1.3 on 2024-11-17 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_job'),
        ('users', '0002_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='startups.job')),
            ],
            options={
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
